### ISSUE TITLE
[1.20.1] While hitting grass, or anything similar you punch yourself in the process.

### ISSUE THREAD

**Issue by Gbergz** [ldtteam/cleanswing#1]
While hitting grass, or anything similar you punch yourself in the process. (It's possible to unalive yourself with this).

Video showing problem: https://streamable.com/xc5nsp

Versions: 
Clean Swing: 1.0
MC: 1.20.1
Forge: 47.1.3

**Comment by Raycoms** [comment]
On it

**Comment by Raycoms** [comment]
Fixed

**Comment by Gbergz** [comment]
Thanks! :) 

But there's a new issue or rather annoying issue, that you cant break grass sometimes at all, or blocks similar to grass etc.

Video showing better: https://streamable.com/b453lo

**Comment by Raycoms** [comment]
on it

**Comment by Raycoms** [comment]
Fixed

**Comment by Gbergz** [comment]
Confirmed, thanks!

**Comment by Gbergz** [comment]
While I am here, damage is not being correctly applied from the weapon/item you're attacking with through grass and similar.
Edit: Seems sweeping edge isn't applied either. 
Edit: 2: Or it is, but the particle effect is missing.

### (Health at the top) (only half a heart with a diamond sword to a pig through grass)

### Video:
https://streamable.com/nluixl

**Comment by Raycoms** [comment]
Hmm, its possible that the particle effect, is applied very early on, compared to where I have to cancel and inject this. The dev of the particle effect would have to apply that later then I guess

**Comment by Gbergz** [comment]
Talking about the vanilla sweeping particle by the way.
Edit.
This one:
![bild](https://github.com/ldtteam/cleanswing/assets/26634554/ff630813-739b-437f-b899-456add55e7ee)

**Comment by Gbergz** [comment]
Anyway, any update on the damage issue through the grass? Main issue really.

**Comment by Raycoms** [comment]
I thought you meant the damage was being applied correctly in your last comment? Just the effects dont show it?

**Comment by Gbergz** [comment]
no, I meant the opposite + sweeping edge (& particle isn't being applied)

**Comment by Gbergz** [comment]
Hey, just want to tell you that the issues are fixed now in v1.3, thank you!
