### ISSUE TITLE
[1.21][Neoforge] Crash when breaking sugar cane

### ISSUE THREAD

**Issue by ffuentesm** [ldtteam/cleanswing#2]
Crash log: [https://pastebin.com/DxHKHduA](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252fDxHKHduA)

Neoforge: 21.0.40
XaerosWorldMap_1.38.8_NeoForge_1.21.jar

cleanswing-1.5.jar   
 
When I try to break the sugar cane, the game crashes.

**Comment by Raycoms** [comment]
Breaking neoforge changes, will update

**Comment by Raycoms** [comment]
fixed
