### ISSUE TITLE
Mod compatibility: Integrated Dynamics.

### ISSUE THREAD

**Issue by Jophire** [ldtteam/cleanswing#6]
Currently, it looks like you are not checking for fake players, which causes the Player Simulator from Integrated Dynamics to fail.

This might also be impacting other fake player instances, but am not 100% on that.

Adding a 
```
&&  !(event.getEntity() instanceof FakePlayer)
```
to line 26 should solve the issue I think.

**Comment by Raycoms** [comment]
Solved
